# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'DemoCollectOC' do
pod 'CocoaLumberjack'
pod 'JSPatch'
pod 'SDWebImage'
pod 'SDWebImage/WebP'
pod 'lottie-ios'
pod 'Aspects'
end

